# Generated by Django 5.0 on 2023-12-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, help_text='설명 또는 메모', max_length=255, null=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('ON', 'Ongoing'), ('CO', 'Completed')], default='PE', max_length=2)),
                ('start_dt', models.DateTimeField(help_text='이벤트 노출 시작일')),
                ('end_dt', models.DateTimeField(blank=True, help_text='이벤트 노출 종료일', null=True)),
            ],
        ),
    ]
